createvm_default:
  initialrun: cloudinit
  clone: false
  cluster: CL-OVN
  disksize: 5GiB
  disk_format: "cow" # "raw"
  dns_search: 
    - "spo.local"
  dns_servers:
    - "172.26.76.217"
    - "172.26.76.218"
  memory: 2GiB
  nic:
    name: eth0
    network: cl_ovn_vlan_76
    profile_name: cl_ovn_vlan_76
  nic_boot_protocol: dhcp
  storage_domain: fc_dc_ovn_02
  template: tmp-redos80
  template_version: 0
  timezone: Etc/GMT
  startvm: false
  waitstart: false
  username: "crocadmin"
  userpass: "QAZxsw123"
  pubkey: " "
  operating_system: Linux 
  customscript: ''
  project: "aratner"
  # customscript: |
  #   write_files:
  #   - path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  #     content: |
  #       network: {config: disabled}
  #     permissions: '0644'
  #     owner: root:root
  #   - path: /etc/issue
  #     append: false
  #     content: |
  #       \4
  #       \6
  #   - path: /root/cloudinit-disable.sh
  #     content: |
  #       #!/bin/bash
  #       mv /etc/netplan/50-cloud-init.yaml /etc/netplan/01-static.yaml
  #       systemctl disable cloud-config.service cloud-final.service cloud-init.service cloud-init-local.service
  #       touch /root/cloudinit-disable.done
  #       echo "disabled by cloudinit custom script" > /etc/cloud/cloud-init.disabled
  #     permissions: '0644'
  #     owner: root:root
  #   runcmd:
  #   - [sh, /root/cloudinit-disable.sh]

newvms:
  # - { role: test1, suffix: '1', 
  #     template: tmp-redos80, os: redos_7, 
  #     cpu_cores: 2, memory: 2 GiB, disk1size: 400 GiB, 
  #     ipv4: { method: static, address: 172.25.62.133, netmask: 255.255.255.0, gateway: 172.25.62.1 } 
  #   }
  # - { role: repo, suffix: '1', 
  #     template: tmp-redos80, os: redos_7, 
  #     cpu_cores: 2, memory: 2 GiB, disk1size: 400 GiB, 
  #     ipv4: { method: static, address: 172.25.62.132, netmask: 255.255.255.0, gateway: 172.25.62.1 } 
  #   }
  # - { role: rt, suffix: '1', 
  #     timezone: Europe/Moscow, template: tmp-chr7, os: other_linux, 
  #     cpu_cores: 2, memory: 1 GiB, disk1size: 1 GiB, 
  #     ipv4: { method: static, address: 172.25.62.142, netmask: 255.255.255.0, gateway: 172.25.62.1 } 
  #   }
  # - { role: dc, suffix: '1',
  #     timezone: Russian Standard Time, initialrun: sysprep, os: windows_2022, template: tmp-w2022std-sysprep,
  #     cpu_cores: 4, memory: 8 GiB, disk1size: 50 GiB, 
  #     ipv4: { method: static, address: 172.25.62.128, netmask: 255.255.255.0, gateway: 172.25.62.1 } 
  #   }
  # - { role: dc, suffix: '2', 
  #     timezone: Russian Standard Time, initialrun: sysprep, os: windows_2022, template: tmp-w2022std-sysprep,
  #     cpu_cores: 4, memory: 8 GiB, disk1size: 50 GiB, 
  #     ipv4: { method: static, address: 172.25.62.129, netmask: 255.255.255.0, gateway: 172.25.62.1 } 
  #   }
  # - { role: rdp, suffix: '1', 
  #     timezone: Russian Standard Time, initialrun: sysprep, os: windows_2022, template: tmp-w2022std-sysprep,
  #     cpu_cores: 8, memory: 32 GiB, disk1size: 100 GiB, 
  #     ipv4: { method: static, address: 172.25.62.130, netmask: 255.255.255.0, gateway: 172.25.62.1 } 
  #   }
  # - { role: rdp, suffix: '2', 
  #     timezone: Russian Standard Time, initialrun: sysprep, os: windows_2022, template: tmp-w2022std-sysprep, 
  #     cpu_cores: 8, memory: 32 GiB, disk1size: 100 GiB, 
  #     ipv4: { method: static, address: 172.25.62.131, netmask: 255.255.255.0, gateway: 172.25.62.1 } 
  #   }
  - { role: test, suffix: '1', 
      timezone: Russian Standard Time, initialrun: sysprep, os: windows_11, template: tmp-w11pro-sysprep, 
      cpu_cores: 4, memory: 8 GiB, disk1size: 30 GiB, 
      ipv4: { method: static, address: 172.26.76.219, netmask: 255.255.255.0, gateway: 172.26.76.1 } 
    }
