---
- name: Create vms
  hosts: localhost

  vars_files:
    - zvirt.yml
    - create-vms-zvirt.yml

  pre_tasks:
    - name: Login
      ovirt.ovirt.ovirt_auth:
        url: "https://{{ engine_fqdn }}/ovirt-engine/api"
        password: "{{ engine_password }}"
        username: "{{ engine_user }}"
        ca_file: "{{ engine_cafile }}"

  post_tasks:
    - name: Logoff
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"

  tasks:
    - name: Create VMs
      ansible.builtin.include_role:
        name: create-vm-zvirt
      vars:
        createvm_debug: false
        createvm:
          initialrun: "{{ newvm.initialrun | default(createvm_default.initialrun) }}"
          name: "{{ (newvm.name | default((newvm.project | default(createvm_default.project)) + '_' + (newvm.site | default('')) + newvm.role + (newvm.suffix | default('') | string))) }}"
          ci:
            hostname: "{{ (newvm.hostname | default((newvm.site | default('')) + newvm.role + (newvm.suffix | default('') | string))) }}"
            username: "{{ ansible_user | default(createvm_default.username) }}"
            userpass: "{{ ansible_password | default(createvm_default.userpass) }}"
            pubkey: "{{ ansible_ssh_public_key | default(createvm_default.pubkey) }}"
            customscript: "{{ newvm.customscript | default(createvm_default.customscript) }}"
            nic_boot_protocol: "{{ newvm.ipv4.method | default(createvm_default.nic_boot_protocol) }}"
            dns_servers: "{{ newvm.dns_servers | default(createvm_default.dns_servers) }}"
            dns_search: "{{ newvm.dns_search | default(createvm_default.dns_search) }}"
            ipv4_address: "{{ newvm.ipv4.address | default(omit) }}"
            ipv4_netmask: "{{ newvm.ipv4.netmask | default(omit) }}"
            ipv4_gateway: "{{ newvm.ipv4.gateway | default(omit) }}"
          clone: "{{ newvm.clone | default(createvm_default.clone) }}"
          cluster: "{{ newvm.cluster | default(createvm_default.cluster) }}"
          comment: "{{ newvm.role }} {{ newvm.site | default('') }} {{ newvm.project | default(createvm_default.project) }}"
          cpu_cores: "{{ newvm.cpu_cores }}"
          description: "{{ newvm.role }} {{ newvm.site | default('') }} {{ newvm.project | default(createvm_default.project) }}"
          disksize: "{{ newvm.disk1size | default(createvm_default.disksize) }}"
          disk_format: "{{ newvm.disk_format | default(createvm_default.disk_format) }}"
          memory: "{{ newvm.memory | default(createvm_default.memory) }}"
          nics:
            - name: "{{ newvm.nic.name | default(createvm_default.nic.name) }}"
              network: "{{ newvm.nic.network | default(createvm_default.nic.network) }}"
              profile_name: "{{ newvm.nic.profile_name | default(createvm_default.nic.profile_name) }}"
          storage_domain: "{{ newvm.storage_domain | default(createvm_default.storage_domain,omit) }}"
          startvm: "{{ newvm.startvm | default(createvm_default.startvm) }}"
          operating_system: "{{ newvm.os | default('other') }}"
          template: "{{ newvm.template | default(createvm_default.template) }}"
          template_version: "{{ newvm.template_version | default(createvm_default.template_version) }}"
          timezone: "{{ newvm.timezone | default(createvm_default.timezone) }}"
          tags:
            - HA
            - "{{ newvm.project | default(createvm_default.project) }}"
            # - "site_{{ newvm.site }}"
            # - "role_{{ newvm.role }}"
          waitstart: "{{ newvm.waitstart | default(createvm_default.waitstart) }}"
      loop: "{{ newvms }}"
      loop_control:
        loop_var: newvm
        label: "{{ newvm.name | default((newvm.project | default(createvm_default.project)) + '_' + (newvm.site | default('')) + newvm.role + (newvm.suffix | default('') | string)) }}"
